version: "3.9"
services:
  auth:
    build:
      context: ./auth-service
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
  upload:
    build:
      context: ./upload-service
      dockerfile: ./Dockerfile
    ports:
      - "3002:3002"
  event:
    build:
      context: ./event-bus
      dockerfile: ./Dockerfile
    ports:
      - "3003:3003"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"